name: Auto Meme Worker (hourly)

on:
  schedule:
    - cron: '0 * * * *'   # runs at minute 0 every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        working-directory: ./worker
        run: |
          python -m pip install --upgrade pip
          pip install -r worker/requirements.txt

      - name: Run auto_meme_agent.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BACKEND_BASE: ${{ secrets.BACKEND_BASE }}
          SUBREDDITS: memes,dankmemes,ProgrammerHumor
          MIN_UPVOTES: '100'
          FETCH_LIMIT: '25'
        run: |
          python worker/auto_meme_agent.py
